# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_bookings_newcustomerreg_registernewemp_registernewfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewemp',
            name='DOB',
            field=models.DateTimeField(),
        ),
    ]
