# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20200108_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='CheckOutDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='CheckinDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registernewemp',
            name='Desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
