# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_auto_20200108_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='CheckOutDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='CheckinDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='CustomerName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='RoomNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='TotalCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='custID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
